### ISSUE TITLE
crackshot troubles in console

### ISSUE THREAD

**Issue by chillerkraft** [Rocologo/MobHunting#253]
https://pastebin.com/wfXqEfaC

when i use bazooka from crackshotplus and shoot a bunch of pigs, i get spam in console. i did mh debug and re shot the 20 pigs, to show you what's going on. good luck!

**Comment by chillerkraft** [comment]
o and i just realized, the unarmed thing is mcmmo being uncompatible with crackshot sending unarmed levels for using guns.. i dont think thats something u can fix. ive tried contacting mcmmo dev t00thpick about that but havent got a response. still, keeping this open for the reasons orginally posted.

**Comment by Rocologo** [comment]
Oh, it seems that i forgot to create a text line the lang file, but you can create it yourself a the end of the file,

bonus.crackshot.name=Craakshot

And do /mh reload

**Comment by Rocologo** [comment]
I will check my code to see if I can do anything about the mcmmo reward.

**Comment by chillerkraft** [comment]
okay! ill try to remember to do that tomorrow. awesome thanks

**Comment by Rocologo** [comment]
I have looked at the code, and I can fix it so you dont get a mcmmo rewards at all when use crackshot. 

I am currently working on my Jenkins server, so you will have to download a snapshot where both errors  should be fixed from my dropbox:
https://www.dropbox.com/s/mqrj32cxtd4g7gk/original-MobHunting-5.0.0-SNAPSHOT-Blocal.jar?dl=0

**Comment by chillerkraft** [comment]
done. all good. thanks!

**Comment by chillerkraft** [comment]
mcmmo archery not fixed still getting levels for archery

also included problem i noticed in console

https://pastebin.com/74B59SYG

**Comment by chillerkraft** [comment]
i just noticed this error at startup
https://pastebin.com/mDWdEsUb

**Comment by Rocologo** [comment]
The last error is not related to CrackShot but it looks like det bStat developer has changed something in his code, which has affected my code  :-(

**Comment by chillerkraft** [comment]
can you try to fix the archery thing still?

**Comment by Rocologo** [comment]
I am looking at it, but I need to know which weapon you used to get this error so I can try to replicate the error. Then it is easier to fix.

**Comment by Rocologo** [comment]
PLease use this build for testing the archery problem

https://www.dropbox.com/s/d9t0vlodkij63aq/MobHunting-5.0.0-SNAPSHOT-Blocal.jar?dl=1

and show me the debug information before and after the error in the console.

**Comment by chillerkraft** [comment]
https://pastebin.com/mJPBuKaa

**Comment by chillerkraft** [comment]
i was still getting archery skill

**Comment by Rocologo** [comment]
Im sorry I cant guess what you are doing??? In the pastebin it looks like you are in creative? If you are in creative mode and get archery skills. The I dont thing the problem is with MobHunting

Please explain more detailed what I have to do to replicate this bug?

**Comment by chillerkraft** [comment]
o okay yea it's with mcmmo i just thought u were sayin u could fix it through your plugin
i fixed the problem by beginning to setup my guns to use snowballs as projectiles instead of arrows

**Comment by Rocologo** [comment]
If you explain to me what you do with your CrackShot gun firing arrows, I might be able to fix it.

How do I make a CrackShot gun which fires arrows? SO I can test this?

**Comment by Rocologo** [comment]
Can I close this one?

**Comment by Rocologo** [comment]
Fixed in V5.0.0
