### ISSUE TITLE
Displayname format

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#655]
Spigot 1.16.1
MH 7.0.5-b1032

Despite this setting (in four places) in MobHunting/config.yml
```
    skull:
      displayname_format: '{value}'
```
bags are labelled `( {value})` -- that is, with parentheses (and a blank space before the value). Please allow just the number value.

**Comment by Rocologo** [comment]
Im working on this now.

**Comment by SlimeDog** [comment]
MH 7.0.5-b1036

```
    skull:
      displayname_format: '{value}'
```
is respected, but
```
    text_color: GOLD
```
is not; the text is white.

**Comment by Rocologo** [comment]
I think it is fixed in Build 1038 + 
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Rocologo** [comment]
PS. Im not sure if text_color is used anymore, use colorcodes in display_format instead

**Comment by SlimeDog** [comment]
The issue persists in b1038.

Removing the deprecated nodes from MobHunting/config.yml is fine. Anytime. However in BagOfGold/bagofgoldcore.yml
```
reward:
    # Here you can set of the color of the number above the dropped item.
    # Use color names like WHITE, RED, BLUE, GOLD
    text_color: GOLD
```
is not observed. Since it is new to 7.5.0, it is unclear why not. It has always been possible to add color codes to `displayname_format`, but I didn't since it seemed that `text_color` (and previously the deprecated `drop_money_on_ground_text_color`) ought to work as documented.

**Comment by Rocologo** [comment]
I have to investigate where text_color is used, it does not make sense to me anymore to have this. But as you probaply know I have made many changes this time and is fighting the bugs :-(

**Comment by Rocologo** [comment]
Ahh. now I know where the color is used. Its used in money commands when you f.ex. type /mh money balance. The output is not formatted with the display_name yet.

**Comment by SlimeDog** [comment]
I tried adding color codes to `displayname_format`:
```
      displayname_format: '&6{value}'
```
(and restarting the server -- reload didn't seem to understand that change) at which point no BagOfGold was dropped. Removing the color code (and restarting the server) reinstated the BagOfGold drops, but with `displayname_format` in white. Please test this functionality and get either `text_color` or color codes to work. Either method would be fine.

**Comment by Rocologo** [comment]
I had simpley forgot to reload Core config when using /mh reload or /bag reload - this is fixed in build 1040 - Im testing right now...

**Comment by Rocologo** [comment]
I works... I can change the format and reload and see the change on new items

**Comment by Rocologo** [comment]
Im not going to change the name zombie_pigman for now. This affects all the server-owners and it is basically the same mob, just a new name. If you try to kill a zombified_piglin you will get the reward for the zombie_pigman. Changing the name is alot harder because I then need to copy old values into the new name.

**Comment by SlimeDog** [comment]
I think this releases to [#654](https://github.com/Rocologo/MobHunting/issues/654) not this issue.

**Comment by Rocologo** [comment]
Correct.

**Comment by Rocologo** [comment]
I this ticket Im only missing the "text_color" and to be honest, Im not sure how I should use this?

**Comment by SlimeDog** [comment]
I think `text_color` should apply to the displayed name of the dropped item, which in my case is '{value}'. So with my configuration settings, the displayed value should be gold, not white.

Tangentially, if `displayname_format` includes a color code, it should be used. At present, it disables MH rewards.

**Comment by Rocologo** [comment]
When displayname_format includes colorcodes they are used. I have tested this and this is why I dont see the need for text_color anymore. Does colorcodes in displayname_format not work for you?

**Comment by SlimeDog** [comment]
I don't care which method, so long as it works. It does not work for me at present. As reported above, BagOfGold/bagofgoldcore.yml includes
```
      displayname_format: '&6{value}'
```
in all four places where `displayname_format` is defined. After server restart (or reload -- both work), that configuration effectively disables MH drops, although the player account is incremented with the appropriate reward. Debug mode claims that a SKULL was dropped, but it was not visible across more than ten tests, both close (sword/axe) and long distance (bow&arrow).

If I remove the color code, the SKULL is dropped.

Is that the correct placement and designation of the color code?

**Comment by SlimeDog** [comment]
Here is another hint from the debug. After a series of long-distance kills, I went to pick up the entity drops and experience orbs. MH reports pick-up of "no-name" items. Are the skulls invisible?
```
[00:36:24] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog picked up a  with a value: 50 (# of rewards left=6)(PickupRewards)
[00:36:28] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog picked up a  with a value: 50 (# of rewards left=5)(PickupRewards)
[00:36:29] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog picked up a  with a value: 50 (# of rewards left=4)(PickupRewards)
[00:36:32] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog picked up a  with a value: 50 (# of rewards left=3)(PickupRewards)
[00:36:34] [Server thread/INFO]: [MobHunting] [Debug] _SlimeDog picked up a  with a value: 50 (# of rewards left=2)(PickupRewards)
```

**Comment by Rocologo** [comment]
No this happens because the reward has no displayname. Its only debug information, in next release it will show the name or the ItemType (SKULL, ITEM, KILLER, KILLED)

**Comment by SlimeDog** [comment]
I would be happy to run whatever debugging you want, to resolve this issue. I do not know what else I can do.

**Comment by Rocologo** [comment]
Which issue are you talking about now? The no-name is not an issue, since it is only debug information and it should be solved in 

this snapshot Build 1049

https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by SlimeDog** [comment]
"this issue" = not seeing drops. Debug messages are what they are. I have no idea if the two issues are really the same issue.

**Comment by SlimeDog** [comment]
I'm giving up on this. WHITE is ok.

**Comment by Rocologo** [comment]
Lets close this one then. I will work on text_color at a later stage.

**Comment by SlimeDog** [comment]
Thanks.
